name: Release

on:
  release:
    types: [released]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - run: cabal clean
      - run: cabal build
      - run: cabal sdist
      
      - uses: haskell-actions/hackage-publish@v1.1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          publish: false # upload candidate
